# Generated by Django 5.1.2 on 2024-12-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idproducto', models.IntegerField()),
                ('nombre', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('stock', models.IntegerField()),
                ('idproveedor', models.CharField(max_length=20)),
                ('idsucursal', models.IntegerField()),
                ('notas', models.TextField()),
            ],
        ),
    ]
