# Generated by Django 5.1.2 on 2024-12-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idproducto',
            field=models.IntegerField(null=True),
        ),
    ]
