# Generated by Django 5.1.2 on 2024-12-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('dondecompro', models.CharField(max_length=20)),
                ('quienvendio', models.CharField(max_length=20)),
                ('idproducto', models.IntegerField()),
                ('idcliente', models.IntegerField()),
            ],
        ),
    ]
