# Generated by Django 5.1.2 on 2024-12-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventas',
            old_name='fecha',
            new_name='fecha_venta',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='dondecompro',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='quienvendio',
        ),
        migrations.AddField(
            model_name='ventas',
            name='idempleado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventas',
            name='idsucursal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventas',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='idcliente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='idproducto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
