# Generated by Django 5.1.2 on 2024-12-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='cuenta',
            new_name='idproveedor',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='sexo',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
