# Generated by Django 5.1.2 on 2024-12-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=20)),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=15)),
                ('cuenta', models.IntegerField()),
                ('cempleados', models.IntegerField()),
            ],
        ),
    ]
