# Generated by Django 5.1.2 on 2024-12-05 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales_app', '0002_alter_sucursal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='cuenta',
        ),
    ]
