# Generated by Django 5.1.2 on 2024-12-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idempleados', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('salario', models.FloatField()),
                ('curp', models.CharField(max_length=15)),
                ('fecha_ingreso', models.DateField()),
                ('idsucursal', models.IntegerField(blank=True, null=True)),
                ('puesto', models.CharField(max_length=50)),
            ],
        ),
    ]
