# Generated by Django 5.1.2 on 2024-12-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcliente', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('rfc', models.CharField(max_length=15)),
                ('cuenta', models.IntegerField()),
                ('correo', models.CharField(max_length=50)),
                ('fecha_nac', models.DateField()),
            ],
        ),
    ]
