# Generated by Django 5.1.2 on 2024-12-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='idcliente',
            field=models.IntegerField(null=True),
        ),
    ]
